spring.application.name=quell

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quell}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:quell}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:quell}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# DevTools hot-swap
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
